### ISSUE TITLE
Permissions in FSRepo

### ISSUE THREAD

**Issue by McAviti** [topolik/FSRepo#1]
Ahoj

Thanks for this work, it's just what I was looking for. I plan to use this repository for my photo gallery.
What would be great, though, would be permissions for folders/fileentries. I thought this could be done by either hidden files in the file system itself, or by metadata in the database.
What do you think about that? Help appriciated or is your strategy in another direction?

bye,
~klemens

**Comment by topolik** [comment]
Ahoj :)

Permissions would be fine. I need to discover how to do it but I think it's feasible. I suppose it should be saved inside portal DB because it's will be managed in the portal.

I've put it on the plate for the next version ;)

-- tom

**Comment by McAviti** [comment]
Ahoj Tom

I'm testing FSRepo with my Photo (sub)directory, when accessing the

## repository in the portlet I get a couple of exceptions in the log:

21:23:15,893 ERROR [JDBCExceptionReporter:75] ERROR: duplicate key
value violates unique constraint "ix_9bdcf489"
  Detail: Key (repositoryid, mappedid)=(14403,
bb4cfc88d97fbe2877cebc3e413e8fc9d543686a30693bb0415ea89a3e084afe)

## already exists.

Afterwards, no pics are displayed, just dummy icons -- but that might
by a consecutive error.

What I've learned from the code is that you use a md5 checksum as a
key for a fileentry in the prefs record. I assume that each declared
repo gets its prefs record (type 1000). So might it be that two
identical files lead to that unique constraint violation? If this is
the case might it be a solution to add the file path to the md5
object?

May I ask what was your design decision to store the whole repo in one
prefs record? Is it to have it all in memory and have fast access? Do
you think it's possible to handle quite large repos this way?

Sorry for the bulk of questions - I am still new to that... :)

bye,
~klemens

2012/3/11 Tomáš Polešovský
reply@reply.github.com:

**Comment by topolik** [comment]
Ahoj

Unique constraint - I've seen it also but don't know what's the problem there. The md5 checksum is derived from the whole absolute file path. I rewrote it and from that point I haven't get the exception. It should be fixed for the next version.

One preferences for one repository - the main idea behind is that I don't want to optimize too early :) I need to save somewhere mapping of md5 checksum -> absolute file path, **indexed by the md5 checksum**. And this was the easiest, still working, solution.

I was thinking about it for a while and now I have a different solution that is more efficient - to use Expando for RepositoryEntry. There I can save the file absolute path. This leads to cheap read and write operations which are based just on the current file and don't include all other files.

Thank you for pushing me!

-- tom

**Comment by McAviti** [comment]
Ahoj

I've seen you started the permissions work... :)
Can I already build it and test?

Maybe one suggestion: Since you've got separate prefs for each repo
would it be an idea to cut the repo's root folder from the entry's

## absolute path in FileSystemRepositoryMapper? Something like...

```
    String rootFolderPath =
```

environment.getRepository().getRootFolder().getAbsolutePath();
        String entryPath = file.getAbsolutePath();
        String relativePath =
entryPath.substring(rootFolderPath.length()); // should be tested
        md.reset();
        md.update(relativePath.getBytes());

##         byte[] mdbytes = md.digest();

bye,
~klemens

2012/3/13 Tomáš Polešovský
reply@reply.github.com:

**Comment by topolik** [comment]
Ahoj!

Yes, you can try to build it but I know it doesn't work yet :)

I rewrote the code for Expando and now I don't use FileSystemRepositoryMapper anymore. But your suggestion is a good point and is still valid! I'll remove the Repository path prefix from each file.

Thx.

-- tom
