### ISSUE TITLE
Installation of the web archive

### ISSUE THREAD

**Issue by McAviti** [topolik/FSRepo#3]
On my two test systems the installation by just copying the war file into the tomcat webapps folder did not work (the message "Hook for fsrepo-hook is available for use" did not appear, fsrepo was not at the archive options). This was either for installing the 1.0 version and upgrade to 1.1.
It works by deploying via Liferay's Plugin Installation/Upload File -- I'd suggest to just change the installation hint on the Wiki page.

**Comment by topolik** [comment]
Hi, 

that's strange, because the deployment is the same way in both cases (I thought). I need to look at it.

Thank you for the info.
