### ISSUE TITLE
Media Gallery Image Icons and Preview only work for .png and .jpeg (v1.1)

### ISSUE THREAD

**Issue by ghost** [topolik/FSRepo#5]
Hello,

I have installed this portlet in my liferay installation. Everything work excellent, except that some images preview don't work in Media Gallery.

Only .png and .jpeg work the icon and preview. If the image is for example .bmp or .jpg don't work.

I install 1.0 version of the portlet and all images icon and previews work. I already view the source code but I cannot find the problem in 1.1 version.

**Comment by topolik** [comment]
Hi,

thank you for the report. It should be fixed by  https://github.com/topolik/FSRepo/commit/5e5cb5aa8265ecc3ac5d43a0b3e1a96ce78d5754
