### ISSUE TITLE
Moved content stay in src

### ISSUE THREAD

**Issue by benner999** [topolik/FSRepo#7]
When I move a folder, the data/files in src stay there. Looks like its a copy and not a move.

I tried with one file - and that is moved correct.

**Comment by topolik** [comment]
Thank you, I need to look whether it's my or Liferay's bug.

-- tom

**Comment by topolik** [comment]
So it's Liferay issue - file entries are copied, not moved - https://github.com/liferay/liferay-portal/blob/29cb9a82a3f9c174a60c164e97f58da02df2df35/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppServiceImpl.java#L2997
